### Import

In [1]:
import numpy as np
import pandas as pd

### Fetch the data from the Internet and save it as csv
The following cell only needs to run once. 

In [2]:
# from ucimlrepo import fetch_ucirepo 

# # fetch dataset 
# breast_cancer_wisconsin_original = fetch_ucirepo(id=15) 
  
# # data (as pandas dataframes) 
# X = breast_cancer_wisconsin_original.data.features 
# y = breast_cancer_wisconsin_original.data.targets 

# data = pd.concat([y, X], axis=1)
# data.to_csv("data.csv", index=False)

### Read the data to X and y, and replace B and M (2&4) with 0 and 1

Note that there are missing values. As we got a large dataset, we will just drop the records.

In [2]:
data = pd.read_csv("data.csv")
data.dropna(inplace=True)
X = data.drop("Class", axis=1)
y = data['Class']
y.replace({2: 0, 4: 1}, inplace=True)
print(X.shape, y.shape)

(683, 9) (683,)


In [290]:
a = np.array([1,2,3]).reshape(-1,1)
b=np.array([4,5,6]).reshape(1, -1)
print(a.shape)
print(b.shape)
print(a.dot(b).shape)

(3, 1)
(1, 3)
(3, 3)


In [ ]:
from numpy import random
import matplotlib.pyplot as plt


class Layer:
    num_of_layers = 0
    def __init__(self, input_size, output_size, activation="linear"):
        self.weights = random.rand(input_size+1, output_size)-0.5   # weight[0, x] is bias's weight
        # self.weights[:,:] = 0.6
        self.input_size = input_size
        self.output_size = output_size
        self.activation = activation
        if activation == "linear":
            self.activation_function = lambda x: x
            self.d_activation_function = lambda x: x * 1
        elif activation == "sigmoid":
            self.activation_function = lambda x: 1/(1+np.exp(-x))
            self.d_activation_function = lambda x: self.activation_function(x) * (1 - self.activation_function(x))
        else:
            raise Exception("Wrong activation function")
        Layer.num_of_layers += 1

    def forward_propagation(self, input):   # input should be an array
        input = np.concatenate(([[1], input]))    # add bias = 1
        self.input = input
        output = self.activation_function(input.dot(self.weights))
        self.output = output
        return output
    
    def backward_propagation(self, dl_dy, learning_rate = 0.1):
        # print(f"dl_dy.shape: {dl_dy.shape}")
        # print(f"self.weights.shape: {self.weights.shape}")

        da_dw = self.input.reshape(-1, 1)
        # print(f"da_dw.shape: {da_dw.shape}")

        dl_dw = da_dw.dot(self.d_activation_function(dl_dy.T))
        # print(f"dl_dw.shape: {dl_dw.shape}")

        dl_dx = (self.weights[1:]).dot(self.d_activation_function(dl_dy))
        # print(f"dl_dx.shape: {dl_dx.shape}")

        self.weights -= learning_rate * dl_dw

        # print()
        return dl_dx
        

class Model:
    def __init__(self):
        self.layers = []

    def add(self, layer):
        self.layers.append(layer)

    def show_layers(self):
        for i, l in enumerate(self.layers):
            print(f"Layer {i+1}: ", end="")
            print(f"input size: {l.input_size}, output size: {l.output_size}")

    def predict(self, input):
        prev_output = input
        for layer in self.layers:
            prev_output = layer.forward_propagation(prev_output)
            print(prev_output)
        return prev_output

    def one_cycle(self, input, expected_output):
        pred = self.predict(input)
        error = (expected_output - pred)
        sq_error = (expected_output - pred)**2
        # d(squared error)/d(prediction)
        derror_dpred = -2 * error
        derror_dpred = np.array([derror_dpred])
        dl_dy = derror_dpred
        for layer in reversed(self.layers):
            dl_dy = layer.backward_propagation(dl_dy)

        print()
    
layer1 = Layer(5, 3, activation="sigmoid")
layer2 = Layer(3, 2, activation="sigmoid")
layer3 = Layer(2, 1, activation="linear")


model = Model()
model.add(layer1)
model.add(layer2)
model.add(layer3)
model.show_layers()

input = np.array([5, 8, 3, 2, 1])
expected_output = sum(input*[3, 4, 6, 2, 1])+5
print(expected_output)


for i in range(20):
    model.one_cycle(input, expected_output)

Layer 1: input size: 5, output size: 3
Layer 2: input size: 3, output size: 2
Layer 3: input size: 2, output size: 1
75
[0.90383077 0.66150987 0.02232874]
[0.42972556 0.40456384]
[-0.01360161]

[0.41108853 0.1267539  0.00169344]
[0.49191418 0.43256531]
[20.81612625]

[0.04929096 0.01066601 0.00012598]
[0.53215649 0.46115369]
[37.10903501]

[3.83605527e-03 8.00102725e-04 9.35772810e-06]
[0.53711178 0.46488875]
[48.57961996]

[2.85932938e-04 5.94705407e-05 6.95037971e-07]
[0.53749799 0.4651814 ]
[56.54243453]

[2.12428854e-05 4.41733305e-06 5.16229903e-08]
[0.53752678 0.46520322]
[62.10027563]

[1.57781614e-06 3.28092473e-07 3.83422439e-09]
[0.53752892 0.46520484]
[65.98407354]

[1.17190221e-07 2.43686094e-08 2.84781566e-10]
[0.53752908 0.46520496]
[68.69850994]

[8.70413801e-09 1.80994386e-09 2.11517459e-11]
[0.53752909 0.46520497]
[70.59570402]

[6.46487481e-10 1.34431007e-10 1.57101586e-12]
[0.53752909 0.46520497]
[71.92170826]

[4.80169385e-11 9.98467190e-12 1.16684969e-13]
[0.537529

C:\Users\psamt\AppData\Local\Temp\ipykernel_41104\2113517622.py:17: RuntimeWarning: overflow encountered in exp
  self.activation_function = lambda x: 1/(1+np.exp(-x))
